spring:
    profiles:  # set default profile to 'dev'
        active:
            - dev
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate.format_sql: true