spring:
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        url: jdbc:h2:./demo
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: validate