server:
    port : 8081
    error:
        include-stacktrace: on-param
spring:
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        url: jdbc:h2:file:./demo
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: validate

logging:
    level:
        org.springframework:
            jdbc.core: INFO
        demo.currency.controller: DEBUG